base:
    user: valois
    random_seed: 12346
    logging: INFO

dataset:
    base_name: h264
    data_dir: bytes_learning
    versions: ['v20230930']
    img_norm_mean: [0.485, 0.456, 0.406]
    img_norm_std: [0.229, 0.224, 0.225]
    img_noise: [0.1, 0.08]
    img_jitter: 0.4
    img_hue: 0.2
    h264_padded_seq_len: 100000
    img_size: [224, 224]
    hist_bins: 64

evaluate:
    model_folder: TBD
    model_name: last_model.pt

model:
    device: 'cuda:0'
    select_name: H64
    normalization:
        name: batch_norm
        groups: 1
        momentum: 0.1
    activation:
        name: gelu
        inplace: True
        negative_slope: 0.1
    h264Net:
        final_dim: 1
    byteformer:
        embed_dim: 192
        n_transformer_layers: 12
        n_attn_heads: 3
        ffn_dim: 768
        norm_layer: layer_norm
        pos_emb_drop_p: 0.1
        attn_dropout: 0.0
        ffn_dropout: 0.0
        dropout: 0.1
        vocab_size: 257
        dummy_input_token_length: 48564
        conv_kernel_size: 8
        max_num_tokens: 50000
        sinusoidal_pos_emb: False
        window_sizes: [128]
        stochastic_dropout: 0.0
        padding_index: -1

train:
    batch_size: 5
    batch_size_test: 1
    num_workers: 8
    save_folder: train_logs
    sampler: Sequential
    optimizer: Adam
    learning_rate: 0.005
    decay: 0.5
    patience: 100
    num_epochs: 1000
    clip_gradnorm_max: 0.1
    show_epochs: 25
    criterion: jse
    scheduler: cosine
    scheduler_cosine:
        warmup_iterations: 10
        warmup_init_lr: 0.000000001
        max_iterations: 500
        min_lr: 0.00001
        max_lr: 0.0001

reports:
    # metric, images

